# Generated by Django 2.0.4 on 2018-04-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen_fondo', models.FileField(upload_to='')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
