# Generated by Django 2.0.4 on 2018-06-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_auto_20180614_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
